logging:
  level:
    org:
      pircbotx: OFF
spring:
  datasource:
    url: jdbc:${DB_TYPE}://${DB_IP}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
    dbcp2:
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
    hikari:
      max-lifetime: 600000
    driver-class-name: org.postgresql.Driver
    properties:
      hibernate:
        dialect: PosgreSQLDialect
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  security:
    oauth2:
      client:
        registration:
          osu:
            clientId: ${OSU_OAUTH_CLIENT_ID}
            clientSecret: ${OSU_OAUTH_CLIENT_SECRET}
            redirectUri: ${OSU_OAUTH_REDIRECT_URI}
            authorizationGrantType: authorization_code
            scope:
              - identify
          discord:
            clientId: ${DISCORD_OAUTH_CLIENT_ID}
            clientSecret: ${DISCORD_OAUTH_CLIENT_SECRET}
            redirectUri: ${DISCORD_OAUTH_REDIRECT_URI}
            tokenRedirectUri: "http://localhost:8081/o/token"
            frontUri: "http://localhost:8080"
            authorizationGrantType: authorization_code
            scope:
              - identify
        provider:
          osu:
            authorizationUri: https://osu.ppy.sh/oauth/authorize
            tokenUri: https://osu.ppy.sh/oauth/token
            userInfoUri: https://osu.ppy.sh/api/v2/me
            userNameAttribute: id
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            usernameAttribute: id
app:
  auth:
    tokenSecret: ${APP_AUTH_TOKEN_SECRET}
    tokenExpirationMsec: ${APP_AUTH_TOKEN_EXPIRATION}
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - https://tournabay.com/oauth2/redirect
      - http://localhost:8080/oauth2/redirect
      - http://localhost:8080/oauth2/oauth2-redirect
      - http://localhost:8080/oauth2/osu-oauth2-redirect
      - http://localhost:8080/oauth2/discord-oauth2-redirect
      - https://gottaaimfast.com/oauth2-redirect
      - https://gottaaimfast.com/osu-oauth2-redirect
      - https://gottaaimfast.com/discord-oauth2-redirect
      - https://gafapi.herokuapp.com/oauth2/callback/discord
      - https://gafapi.herokuapp.com/oauth2/callback/osu
