server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-dev
    username: postgres
    password: pass
    tomcat:
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
    dbcp2:
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
    hikari:
      max-lifetime: 600000
      auto-commit: false
    driver-class-name: org.postgresql.Driver
    properties:
      hibernate:
        dialect: PosgreSQLDialect
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  security:
    oauth2:
      client:
        registration:
          osu:
            clientId: 9552
            clientSecret: md6Y4UwjAwTJ3VQAbfwUnzxLlZ6JMRY3ivGJaRkt
            redirectUri: "http://localhost:8080/oauth2/callback/{registrationId}"
            authorizationGrantType: authorization_code
            scope:
              - identify
              - public
          discord:
            clientId: ${DISCORD_OAUTH_CLIENT_ID}
            clientSecret: ${DISCORD_OAUTH_CLIENT_SECRET}
            redirectUri: ${DISCORD_OAUTH_REDIRECT_URI}
            tokenRedirectUri: "http://localhost:8081/o/token"
            frontUri: "http://localhost:8080"
            authorizationGrantType: authorization_code
            scope:
              - identify
        provider:
          osu:
            authorizationUri: https://osu.ppy.sh/oauth/authorize
            tokenUri: https://osu.ppy.sh/oauth/token
            userInfoUri: https://osu.ppy.sh/api/v2/me
            userNameAttribute: id
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            usernameAttribute: id
app:
  auth:
    tokenSecret: q4zerkIg2f2OYALd70CuqOKKpjL6eLOf0RIjtrvK
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - https://tournabay.com/oauth2/redirect
      - http://localhost:8080/oauth2/redirect
      - http://localhost:8080/oauth2/oauth2-redirect
      - http://localhost:8080/oauth2/osu-oauth2-redirect
      - http://localhost:8080/oauth2/discord-oauth2-redirect
      - https://gottaaimfast.com/oauth2-redirect
      - https://gottaaimfast.com/osu-oauth2-redirect
      - https://gottaaimfast.com/discord-oauth2-redirect
      - https://gafapi.herokuapp.com/oauth2/callback/discord
      - https://gafapi.herokuapp.com/oauth2/callback/osu